//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffee_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeHouse
    {
        public System.Guid idGuid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string address { get; set; }
    }
}
